In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
df = pd.read_csv('/kaggle/input/insurance/insurance.csv')
old_df = df.copy()

/kaggle/input/insurance/insurance.csv


In [3]:
df.head(3)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [5]:
print("Before Drop Duplicate",df.duplicated().sum())
df.drop_duplicates(keep='first',inplace=True)
print("After Drop Duplicate",df.duplicated().sum())

Before Drop Duplicate 1
After Drop Duplicate 0


In [6]:
df.head(3)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [7]:
for i in df.columns.tolist():
    print(i)
    display(df[i].unique())
    print("_" * 50)

age


array([19, 18, 28, 33, 32, 31, 46, 37, 60, 25, 62, 23, 56, 27, 52, 30, 34,
       59, 63, 55, 22, 26, 35, 24, 41, 38, 36, 21, 48, 40, 58, 53, 43, 64,
       20, 61, 44, 57, 29, 45, 54, 49, 47, 51, 42, 50, 39])

__________________________________________________
sex


array(['female', 'male'], dtype=object)

__________________________________________________
bmi


array([27.9  , 33.77 , 33.   , 22.705, 28.88 , 25.74 , 33.44 , 27.74 ,
       29.83 , 25.84 , 26.22 , 26.29 , 34.4  , 39.82 , 42.13 , 24.6  ,
       30.78 , 23.845, 40.3  , 35.3  , 36.005, 32.4  , 34.1  , 31.92 ,
       28.025, 27.72 , 23.085, 32.775, 17.385, 36.3  , 35.6  , 26.315,
       28.6  , 28.31 , 36.4  , 20.425, 32.965, 20.8  , 36.67 , 39.9  ,
       26.6  , 36.63 , 21.78 , 30.8  , 37.05 , 37.3  , 38.665, 34.77 ,
       24.53 , 35.2  , 35.625, 33.63 , 28.   , 34.43 , 28.69 , 36.955,
       31.825, 31.68 , 22.88 , 37.335, 27.36 , 33.66 , 24.7  , 25.935,
       22.42 , 28.9  , 39.1  , 36.19 , 23.98 , 24.75 , 28.5  , 28.1  ,
       32.01 , 27.4  , 34.01 , 29.59 , 35.53 , 39.805, 26.885, 38.285,
       37.62 , 41.23 , 34.8  , 22.895, 31.16 , 27.2  , 26.98 , 39.49 ,
       24.795, 31.3  , 38.28 , 19.95 , 19.3  , 31.6  , 25.46 , 30.115,
       29.92 , 27.5  , 28.4  , 30.875, 27.94 , 35.09 , 29.7  , 35.72 ,
       32.205, 28.595, 49.06 , 27.17 , 23.37 , 37.1  , 23.75 , 28.975,
      

__________________________________________________
children


array([0, 1, 3, 2, 5, 4])

__________________________________________________
smoker


array(['yes', 'no'], dtype=object)

__________________________________________________
region


array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

__________________________________________________
charges


array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

__________________________________________________


In [8]:
df['children'] = df.children.astype('str')

In [9]:
for i in df.select_dtypes(include= 'O').columns.tolist():
    print(i)
    msk = df[i].value_counts().reset_index().rename(columns = {"index" : i })
    display(msk)
    fig = px.histogram(msk , x = i , y = 'count', title=f"Value Counts of {i}" , width=700 , height=400 , text_auto=True , color=i)
    fig.show()
    print("_" * 50)

sex


sex  count
0    male    675
1  female    662

__________________________________________________
children


children  count
0        0    573
1        1    324
2        2    240
3        3    157
4        4     25
5        5     18

__________________________________________________
smoker


smoker  count
0     no   1063
1    yes    274

__________________________________________________
region


region  count
0  southeast    364
1  southwest    325
2  northwest    324
3  northeast    324

__________________________________________________


In [10]:
for i in df.select_dtypes(include= 'number').columns.tolist():
    fig = px.histogram(df , x = i , histfunc='avg' , title=f"Distibution of {i}" , width=900 , height=500, marginal='box' , text_auto=True)
    fig.show()
    print("_" * 50)

__________________________________________________


__________________________________________________


__________________________________________________


In [11]:
df.select_dtypes(include = 'number').quantile([0 , 0.1 , 0.2 , 0.35 , 0.5 , 0.65 , 0.8 , 0.95 , 0.99 , 1])

age      bmi       charges
0.00  18.0  15.9600   1121.873900
0.10  19.0  22.9900   2358.524810
0.20  24.0  25.3130   3996.426740
0.35  31.0  28.0000   6550.328080
0.50  39.0  30.4000   9386.161300
0.65  47.0  32.9000  12415.308800
0.80  54.0  35.8600  20269.216958
0.95  62.0  41.1080  41210.049800
0.99  64.0  46.4112  48537.796878
1.00  64.0  53.1300  63770.428010

In [12]:
# List outliers
outliers = df[(df.bmi > 46.5) | (df.charges > 48600)]
outliers_idx = outliers.index
outliers

age     sex     bmi children smoker     region      charges
34     28    male  36.400        1    yes  southwest  51194.55914
116    58    male  49.060        0     no  southeast  11381.32540
175    63  female  37.700        0    yes  southwest  48824.45000
286    46  female  48.070        2     no  northeast   9432.92530
401    47    male  47.520        1     no  southeast   8083.91980
438    52  female  46.750        5     no  southeast  12592.53450
454    32    male  46.530        2     no  southeast   4686.38870
488    44  female  38.060        0    yes  southeast  48885.13561
530    57    male  42.130        1    yes  southeast  48675.51770
543    54  female  47.410        0    yes  southeast  63770.42801
547    54  female  46.700        2     no  southwest  11538.42100
577    31  female  38.095        1    yes  northeast  58571.07448
660    37    male  46.530        3     no  southeast   6435.62370
819    33  female  35.530        0    yes  northwest  55135.40209
847    23    male  50.380        1     no  southeast   2438.05520
860    37  female  47.600        2    yes  southwest  46113.51100
901    60    male  40.920        0    yes  southeast  48673.55880
930    26    male  46.530        1     no  southeast   2927.06470
1047   22    male  52.580        1    yes  southeast  44501.39820
1062   59    male  41.140        1    yes  southeast  48970.24760
1088   52    male  47.740        1     no  southeast   9748.91060
1146   60    male  32.800        0    yes  southwest  52590.82939
1230   52    male  34.485        3    yes  northwest  60021.39897
1241   64    male  36.960        2    yes  southeast  49577.66240
1300   45    male  30.360        0    yes  southeast  62592.87309
1317   18    male  53.130        0     no  southeast   1163.46270

In [13]:
# Drop
df.drop(outliers_idx , axis=0 , inplace=True)

In [14]:
# Check Quantile again
df.select_dtypes(include = 'number').quantile([0 , 0.1 , 0.2 , 0.35 , 0.5 , 0.65 , 0.8 , 0.95 , 0.99 , 1])

age     bmi       charges
0.00  18.0  15.960   1121.873900
0.10  19.0  22.895   2331.519000
0.20  24.0  25.270   3987.926000
0.35  31.0  27.915   6465.928200
0.50  39.0  30.200   9283.562000
0.65  46.0  32.680  12267.069575
0.80  53.0  35.625  19719.694700
0.95  61.5  40.280  39854.111650
0.99  64.0  43.890  46712.491165
1.00  64.0  46.200  48549.178350

In [15]:
# Check outliers again
for i in df.select_dtypes(include= 'number').columns.tolist():
    fig = px.box(df , x = i , title=f"Distibution of {i}" , width=600 , height=300 )
    fig.show()
    print("_" * 50)

__________________________________________________


__________________________________________________


__________________________________________________


In [16]:
df[df.charges > 33500]

age     sex     bmi children smoker     region      charges
14     27    male  42.130        0    yes  southeast  39611.75770
19     30    male  35.300        0    yes  southwest  36837.46700
23     34  female  31.920        1    yes  northeast  37701.87680
29     31    male  36.300        2    yes  southwest  38711.00000
30     22    male  35.600        0    yes  southwest  35585.57600
...   ...     ...     ...      ...    ...        ...          ...
1301   62    male  30.875        3    yes  northwest  46718.16325
1303   43    male  27.800        0    yes  southwest  37829.72420
1308   25  female  30.200        0    yes  southwest  33900.65300
1313   19  female  34.700        2    yes  southwest  36397.57600
1323   42  female  40.370        2    yes  southeast  43896.37630

[133 rows x 7 columns]

In [17]:
print("old_df shape",old_df.shape[0])
print("total droped & needed ",((old_df.shape[0] - df.shape[0]) +133))
print("Precentage droped & needed ",round( (((old_df.shape[0] - df.shape[0]) +133) / old_df.shape[0]) * 100, 2),"%")

old_df shape 1338
total droped & needed  160
Precentage droped & needed  11.96 %


In [18]:
corr = df.select_dtypes(include='number').corr()
px.imshow(corr , width=500 , height=500 , text_auto=True, title='Correlation' , color_continuous_scale=px.colors.sequential.Agsunset)

In [19]:
for i in ['age','bmi']:
    print(i)
    fig = px.scatter(df , x=i ,y='charges',width=700,height=400,title=f'{i} vs charges')
    fig.show()
    print("__"* 50)

age


____________________________________________________________________________________________________
bmi


____________________________________________________________________________________________________


In [20]:
def bmi (x):
    if x < 18.5:
        return 'Underweight'
    elif 18.5 <= x <= 24.9:
        return 'Healthy'
    elif 24.9 <= x <= 29.9:
        return 'Overweight'
    elif x > 29.9:
        return 'Obese'
    else:
        np.nan
df['bmi_cat'] = df.bmi.apply(bmi)
df['bmi_cat'].value_counts()

bmi_cat
Obese          689
Overweight     380
Healthy        222
Underweight     20
Name: count, dtype: int64

In [21]:
df.head(1)

age     sex   bmi children smoker     region    charges     bmi_cat
0   19  female  27.9        0    yes  southwest  16884.924  Overweight

In [22]:
# ! pip install category_encoders

# Libraries
from sklearn.model_selection import train_test_split
from category_encoders import OneHotEncoder
from sklearn.preprocessing import RobustScaler , PolynomialFeatures
from sklearn.pipeline import Pipeline , make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression , Ridge , Lasso
from sklearn.metrics import r2_score , mean_squared_error

# Spliting
ml_df = df.copy()
x = ml_df.drop('charges' , axis=1)
y = ml_df['charges']
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state= 40)

# Feature Organization
cat = ['sex', 'children', 'smoker', 'region','bmi_cat']
num = ['age', 'bmi']

In [23]:
num_transformation = Pipeline(steps = [("Scaler" , RobustScaler())])
cat_transformation = Pipeline(steps = [("Encoder" , OneHotEncoder())])

# Processor
Processor = ColumnTransformer(transformers = [('Scaler' , num_transformation , num) , ('Encoder' , cat_transformation,cat )])

# Transform to x_train , x_test
x_train_proc = Processor.fit_transform(x_train)
x_test_proc = Processor.transform(x_test)

Processor

ColumnTransformer(transformers=[('Scaler',
                                 Pipeline(steps=[('Scaler', RobustScaler())]),
                                 ['age', 'bmi']),
                                ('Encoder',
                                 Pipeline(steps=[('Encoder', OneHotEncoder())]),
                                 ['sex', 'children', 'smoker', 'region',
                                  'bmi_cat'])])

In [24]:
LR = LinearRegression()
LR.fit(x_train_proc , y_train)

y_pred = LR.predict(x_test_proc)

print("RMSW Accuracy : ",np.sqrt(mean_squared_error(y_test, y_pred)))
print('R2:', r2_score(y_test, y_pred))

RMSW Accuracy :  5790.567245524423
R2: 0.7731459430261844


In [25]:
# @title 🔹 Model 2 (Polynomial Regression)
Poly = PolynomialFeatures(degree=2)
x_train_poly = Poly.fit_transform(x_train_proc)
x_test_poly = Poly.transform(x_test_proc)

LR_poly = LinearRegression()
LR_poly.fit(x_train_poly , y_train)

print("Train Score :" ,LR_poly.score(x_train_poly , y_train))
print("Test Score :" ,LR_poly.score(x_test_poly , y_test))

Train Score : 0.8632204778143114
Test Score : -3.5315944883112855e+21


In [26]:
Poly_Ridge = Ridge()
x_train_poly_L2 = Poly_Ridge.fit(x_train_poly , y_train)

y_pred_poly_L2 = x_train_poly_L2.predict(x_test_poly)

print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_poly_L2)))
print('R2:', r2_score(y_test, y_pred_poly_L2))
print('Train score:', x_train_poly_L2.score(x_train_poly, y_train))
print('Test score:', x_train_poly_L2.score(x_test_poly, y_test))

RMSE: 4369.47722103135
R2: 0.8708295148179487
Train score: 0.8635584043942344
Test score: 0.8708295148179487


In [27]:
for D in [2,3,4,5,6,7]:
    Pipeline_Ploy = make_pipeline(PolynomialFeatures(D), Ridge(alpha=100))
    Pipeline_Ploy.fit(x_train_proc , y_train)
    y_pred = Pipeline_Ploy.predict(x_test_proc)
    print(f"Degree {D}")
    print("RMSE ",np.sqrt(mean_squared_error(y_test , y_pred)))
    print('R2:', r2_score(y_test, y_pred))
    print("_"*30)

Degree 2
RMSE  4490.456780601246
R2: 0.863577698128529
______________________________
Degree 3
RMSE  4320.519176451455
R2: 0.8737078939104407
______________________________
Degree 4
RMSE  4434.493778447769
R2: 0.8669568767961549
______________________________
Degree 5
RMSE  4645.0711249997275
R2: 0.8540214423927402
______________________________
Degree 6
RMSE  4929.809954458391
R2: 0.8355761979226085
______________________________
Degree 7
RMSE  5363.899471039544
R2: 0.805344987660626
______________________________


In [ ]:
Pipeline_Ploy = make_pipeline(PolynomialFeatures(degree=3), Ridge(alpha=100))

x_train_poly_L2_d3 = Pipeline_Ploy.fit(x_train_poly , y_train)
y_pred_poly_L2_d3 = x_train_poly_L2_d3.predict(x_test_poly)

print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_poly_L2_d3)))
print('R2:', r2_score(y_test, y_pred_poly_L2_d3))
print('Train score:', x_train_poly_L2_d3.score(x_train_poly, y_train))
print('Test score:', x_train_poly_L2_d3.score(x_test_poly, y_test))

In [ ]:
Pipeline_Ploy = make_pipeline(PolynomialFeatures(degree=3), Lasso(alpha=1))

x_train_poly_L2_d3 = Pipeline_Ploy.fit(x_train_poly , y_train)
y_pred_poly_L2_d3 = x_train_poly_L2_d3.predict(x_test_poly)

print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_poly_L2_d3)))
print('R2:', r2_score(y_test, y_pred_poly_L2_d3))
print('Train score:', x_train_poly_L2_d3.score(x_train_poly, y_train))
print('Test score:', x_train_poly_L2_d3.score(x_test_poly, y_test))

In [ ]:
def Log (x):
    return np.log1p(x)

y_train_log = Log(y_train)
y_test_log = Log(y_test)

Pipeline_Ploy = make_pipeline(PolynomialFeatures(degree=3), Ridge(alpha=100))

x_train_poly_L2_d3 = Pipeline_Ploy.fit(x_train_poly , y_train_log)
y_pred_poly_L2_d3 = x_train_poly_L2_d3.predict(x_test_poly)

print('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred_poly_L2_d3)))
print('R2:', r2_score(y_test_log, y_pred_poly_L2_d3))
print('Train score:', x_train_poly_L2_d3.score(x_train_poly, y_train_log))
print('Test score:', x_train_poly_L2_d3.score(x_test_poly, y_test_log))

In [ ]:
from sklearn.linear_model import SGDRegressor

def Log (x):
    return np.log1p(x)

y_train_log = Log(y_train)
y_test_log = Log(y_test)

SGD = SGDRegressor(penalty='l2' , alpha=10 , max_iter=10000 , eta0=0.01 , random_state=0 ,tol=1e-3)
SGD_Poly = make_pipeline(PolynomialFeatures(degree = 3) , SGD)

SGD_Poly.fit(x_train_proc , y_train_log.ravel())
y_pred_SGD_train = SGD_Poly.predict(x_train_proc)
y_pred_SGD = SGD_Poly.predict(x_test_proc)

print("SGD train score" , SGD_Poly.score(x_train_proc , y_train_log))
print("SGD test score" , SGD_Poly.score(x_test_proc , y_test_log))
print("RMSW Train:",np.sqrt(mean_squared_error(y_train_log , y_pred_SGD_train)))
print("RMSW test:",np.sqrt(mean_squared_error(y_test_log , y_pred_SGD)))